### ISSUE TITLE
Rename figure names

### ISSUE THREAD

**Issue by jiweiqi** [jiweiqi/CellBox.jl#10]
* when we have a lot of figures, it becomes inconvenient to locate the plot of loss and p. This can be improved by prefix the loss plot with a number `0` or `a`.

**Comment by DesmondYuan** [comment]
I/O restructured in 27df32d0a41b7693f5de269604c25d7c23c6d685

https://github.com/jiweiqi/CellBox.jl/blob/27df32d0a41b7693f5de269604c25d7c23c6d685/spilt/header.jl#L31

Would this solve the issue?
