### ISSUE TITLE
loss in testing in not loaded during restart

### ISSUE THREAD

**Issue by jiweiqi** [jiweiqi/CellBox.jl#11]
https://github.com/jiweiqi/CellBox.jl/blob/e9f112446718d81a9fd601335f7759c05bc6f20f/spilt/callback.jl#L76

**Comment by jiweiqi** [comment]
The inference loss as well.

**Comment by DesmondYuan** [comment]
String loading added here 27df32d0a41b7693f5de269604c25d7c23c6d685

https://github.com/jiweiqi/CellBox.jl/blob/27df32d0a41b7693f5de269604c25d7c23c6d685/spilt/callback.jl#L75-L78
