### ISSUE TITLE
discussions on adding noise

### ISSUE THREAD

**Issue by jiweiqi** [jiweiqi/CellBox.jl#14]
https://github.com/jiweiqi/CellBox.jl/blob/47e8652a3d38d7189fca12b763ab6818f310c586/spilt/network.jl#L62

Initially, I was thinking of adding relative noise, e.g., 1% of the signal. However, after realizing that the signal is in log-scale already, we shouldn't use "relative noise" here, instead, we should use 

`ode_data += randn(size(ode_data)) .* noise `

BTW, adding noise is pretty useful to regularize the parameters.

**Comment by DesmondYuan** [comment]
Implemented at b3f0bc36a57e7757da3e724215c782b216d5825e
