### ISSUE TITLE
LHS sampling for \mu generation

### ISSUE THREAD

**Issue by DesmondYuan** [jiweiqi/CellBox.jl#3]

**Comment by jiweiqi** [comment]
example at https://github.com/DENG-MIT/CRNN/blob/main/robertson/rober_crnn.jl

```Julia
using LatinHypercubeSampling

randomLHC(n_exp, 2)
```

**Comment by jiweiqi** [comment]
LHS sampling can be activated at https://github.com/jiweiqi/CellBox.jl/blob/aa1d808145008655834a152440088861e9873b46/spilt/cellbox.jl#L28
It is based on the following package
https://github.com/jiweiqi/CellBox.jl/blob/aa1d808145008655834a152440088861e9873b46/spilt/header.jl#L11

**Comment by DesmondYuan** [comment]
Beautiful! 

Question: if we want to apply sparsity for \mu, how should we combine that with LHC?

**Comment by jiweiqi** [comment]
Just did at
https://github.com/jiweiqi/CellBox.jl/blob/4b77faf13bf6ec738fd37f9bf7ddaa3ea61ec9ac/spilt/cellbox.jl#L34

**Comment by DesmondYuan** [comment]
Fantastic!
