### ISSUE TITLE
Add inference loss

### ISSUE THREAD

**Issue by DesmondYuan** [jiweiqi/CellBox.jl#4]
- Add a loss metric for parameter evaluation
- Record and plot both prediction performance and inference performance

**Comment by DesmondYuan** [comment]
Implemented in 09cc46afffc704b96a08ffa1a315517a37b9f499  0c00a66b74e5b6620aa2c9d61d2ef3bf65c09bc3 by @judyueshen 

https://github.com/jiweiqi/CellBox.jl/blob/0c00a66b74e5b6620aa2c9d61d2ef3bf65c09bc3/spilt/network.jl#L29-L35

**Comment by jiweiqi** [comment]
It might be a good idea to add the scatter plot of p/w as well, something @judyueshen has done before.

**Comment by jiweiqi** [comment]
* We might plot w during the training as well.
* To do that, we might not want to generate a new figure for each iteration. So that we can simply use `cbp(p, 0)`

**Comment by jiweiqi** [comment]
This can be done by adding `cbp(p, 0)` at https://github.com/jiweiqi/CellBox.jl/blob/e9f112446718d81a9fd601335f7759c05bc6f20f/spilt/callback.jl#L53

**Comment by DesmondYuan** [comment]
Done here d619a2d7577bf9fff39398225667352e87e5d5ab
