### ISSUE TITLE
Add early stopping

### ISSUE THREAD

**Issue by DesmondYuan** [jiweiqi/CellBox.jl#5]
As used in the original CellBox tensorflow codes

**Comment by jiweiqi** [comment]
I have tried to spilt the code into several separate files. If you like, you can put this part into the file `callback.jl` at https://github.com/jiweiqi/CellBox.jl/blob/aa1d808145008655834a152440088861e9873b46/spilt/callback.jl#L56

**Comment by DesmondYuan** [comment]
Thanks @jiweiqi! Now fully implemented at commit 81d3577382cc9e115d23050234ebc335b6fd54c9

the major function is
https://github.com/jiweiqi/CellBox.jl/blob/c99a16d1092bdf0783906c703eaac79b1cd5a213/spilt/callback.jl#L62-L77

**Comment by jiweiqi** [comment]
Looks like there is some issue with the changing directory at
https://github.com/jiweiqi/CellBox.jl/blob/0c00a66b74e5b6620aa2c9d61d2ef3bf65c09bc3/spilt/header.jl#L15

What (current) directory you will suppose to run the code? I can not include("header.jl")

**Comment by jiweiqi** [comment]
Fixed the issue in rm folders when it doesn't exist at
https://github.com/jiweiqi/CellBox.jl/blob/4b77faf13bf6ec738fd37f9bf7ddaa3ea61ec9ac/spilt/header.jl#L30
