### ISSUE TITLE
Using single time steps (ntotal=1) leads to bad plotting

### ISSUE THREAD

**Issue by DesmondYuan** [jiweiqi/CellBox.jl#6]
![i_exp_77](https://user-images.githubusercontent.com/20073463/107074558-c2c2ba00-679d-11eb-86bd-b74b6e89f109.png)

What should be the best way to fix this? @jiweiqi

**Comment by jiweiqi** [comment]
A quick workaround is passing additional arguments to the prediction to disable the `saveat`, instead of output all of the inner datapoints.
https://github.com/jiweiqi/CellBox.jl/blob/main/spilt/network.jl#L65
Change the plotting functions as well.

**Comment by DesmondYuan** [comment]
> A quick workaround is passing additional arguments to the prediction to disable the `saveat`, instead of output all of the inner datapoints.
> https://github.com/jiweiqi/CellBox.jl/blob/main/spilt/network.jl#L65
> Change the plotting functions as well.
> 
> Something like
> 
> ```julia
> function predict_neuralode(u0, p, i_exp=1, batch=ntotal; dense=false)
>     global μ = μ_list[i_exp, 1:ns]
>     _prob = remake(prob, p=p, tspan=[0, ts[batch]])
>     pred = Array(solve(_prob, Tsit5(), saveat=ts[1:batch], sensealg=InterpolatingAdjoint()))
>     return pred
> end
> ```

Sounds perfect. Let me implement it and test

**Comment by DesmondYuan** [comment]
Implemented in 4a0711b301e5410d8d7a8e5793040d0706b739c1
* add config flag `nplot` for num of points when plot solution
* add flag `saveat` as an option in function `predict_neuralode()`
* https://github.com/jiweiqi/CellBox.jl/blob/4a0711b301e5410d8d7a8e5793040d0706b739c1/cellbox/network.jl#L78-L89

![i_exp_7](https://user-images.githubusercontent.com/20073463/108436093-a5f79f00-71ff-11eb-962a-0e1f4950f656.png)
